//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CerinfoNur.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_prestamo
    {
        [Key]
        public int id_prestamo { get; set; }
        public int id_estudiante { get; set; }
        public int id_multa { get; set; }
        public int id_libro { get; set; }
        public System.DateTime fecha_devolucion { get; set; }
        public System.DateTime fecha_prestamo { get; set; }
        public int dias_prestado { get; set; }
        public int id_administrativo { get; set; }
    
        public virtual tbl_administrativo tbl_administrativo { get; set; }
        public virtual tbl_estudiante tbl_estudiante { get; set; }
        public virtual tbl_libro tbl_libro { get; set; }
        public virtual tbl_multa tbl_multa { get; set; }
    }
}
