//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CerinfoNur.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_usuario()
        {
            this.tbl_administrativo = new HashSet<tbl_administrativo>();
            this.tbl_estudiante = new HashSet<tbl_estudiante>();
        }
        [Key]
        [Required]
        public string id_usuario { get; set; }
        [Required]
        [Range(6, 250)]
        public string contrasena { get; set; }
        [Required]
        public string nombre_usuario { get; set; }
        [Required]
        public string paterno_usuario { get; set; }
        [Required]
        public string materno_usuario { get; set; }
        [Required]
        public string tipo_usuario { get; set; }

        [Required]
        [EmailAddress(ErrorMessage ="Email Invalido")]
        public string correo { get; set; }
       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_administrativo> tbl_administrativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_estudiante> tbl_estudiante { get; set; }
    }
}
