//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CerinfoNur.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_bloqueo
    {
        [Key]
        public int id_bloqueo { get; set; }
        public int id_estudiante { get; set; }
        public System.DateTime fecha_bloqueo { get; set; }
        public string detalle_bloqueo { get; set; }
        public double monto_bloqueo { get; set; }
    
        public virtual tbl_estudiante tbl_estudiante { get; set; }
    }
}
