//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CerinfoNur.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_libro()
        {
            this.tbl_prestamo = new HashSet<tbl_prestamo>();
        }
        [Key]
        public int id_libro { get; set; }
        public int id_autor { get; set; }
        public int id_genero { get; set; }
        public int id_idioma { get; set; }
        public int id_material { get; set; }
        public int id_sigtop { get; set; }
        public string titulo_libro { get; set; }
        public string tomo_libro { get; set; }
        public int id_area { get; set; }
        public string edicion_libro { get; set; }
        public string editorial_libro { get; set; }
        public string ano_libro { get; set; }
        public string lugar_publicacion_libro { get; set; }
        public string ano_publicacion_libro { get; set; }
        public int id_targeta { get; set; }
    
        public virtual tbl_area tbl_area { get; set; }
        public virtual tbl_autor tbl_autor { get; set; }
        public virtual tbl_genero tbl_genero { get; set; }
        public virtual tbl_idioma tbl_idioma { get; set; }
        public virtual tbl_material tbl_material { get; set; }
        public virtual tbl_sigtop tbl_sigtop { get; set; }
        public virtual tbl_tarjeta tbl_tarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_prestamo> tbl_prestamo { get; set; }
    }
}
