//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CerinfoNur.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cerinfoEntities : DbContext
    {
        public cerinfoEntities()
            : base("name=cerinfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_administrativo> tbl_administrativo { get; set; }
        public virtual DbSet<tbl_area> tbl_area { get; set; }
        public virtual DbSet<tbl_autor> tbl_autor { get; set; }
        public virtual DbSet<tbl_bloqueo> tbl_bloqueo { get; set; }
        public virtual DbSet<tbl_estudiante> tbl_estudiante { get; set; }
        public virtual DbSet<tbl_genero> tbl_genero { get; set; }
        public virtual DbSet<tbl_idioma> tbl_idioma { get; set; }
        public virtual DbSet<tbl_libro> tbl_libro { get; set; }
        public virtual DbSet<tbl_material> tbl_material { get; set; }
        public virtual DbSet<tbl_multa> tbl_multa { get; set; }
        public virtual DbSet<tbl_prestamo> tbl_prestamo { get; set; }
        public virtual DbSet<tbl_sigtop> tbl_sigtop { get; set; }
        public virtual DbSet<tbl_tarjeta> tbl_tarjeta { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
    
        public virtual int insertarusuario(string pid_usuario, string pcontrasena, string pnombre_usuario, string ppaterno_usuario, string pmaterno_usuario, string ptipo_usuario, string pcorreo)
        {
            var pid_usuarioParameter = pid_usuario != null ?
                new ObjectParameter("pid_usuario", pid_usuario) :
                new ObjectParameter("pid_usuario", typeof(string));
    
            var pcontrasenaParameter = pcontrasena != null ?
                new ObjectParameter("pcontrasena", pcontrasena) :
                new ObjectParameter("pcontrasena", typeof(string));
    
            var pnombre_usuarioParameter = pnombre_usuario != null ?
                new ObjectParameter("pnombre_usuario", pnombre_usuario) :
                new ObjectParameter("pnombre_usuario", typeof(string));
    
            var ppaterno_usuarioParameter = ppaterno_usuario != null ?
                new ObjectParameter("ppaterno_usuario", ppaterno_usuario) :
                new ObjectParameter("ppaterno_usuario", typeof(string));
    
            var pmaterno_usuarioParameter = pmaterno_usuario != null ?
                new ObjectParameter("pmaterno_usuario", pmaterno_usuario) :
                new ObjectParameter("pmaterno_usuario", typeof(string));
    
            var ptipo_usuarioParameter = ptipo_usuario != null ?
                new ObjectParameter("ptipo_usuario", ptipo_usuario) :
                new ObjectParameter("ptipo_usuario", typeof(string));
    
            var pcorreoParameter = pcorreo != null ?
                new ObjectParameter("pcorreo", pcorreo) :
                new ObjectParameter("pcorreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertarusuario", pid_usuarioParameter, pcontrasenaParameter, pnombre_usuarioParameter, ppaterno_usuarioParameter, pmaterno_usuarioParameter, ptipo_usuarioParameter, pcorreoParameter);
        }
    }
}
